server {
  listen 80;
  index index.html;
  root /app/collected_static;
    
  client_max_body_size 20M;

  location /api/ {
    proxy_pass http://backend:8000/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
  
  location /admin/ {
    proxy_pass http://backend:8000/admin/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /media/ {
    alias /app/media/;
    try_files $uri =404;
  }

  location ~ ^/static/(admin|rest_framework)/ {
    root /;
    try_files $uri =404;
  }

  location / {
    root /static;
    try_files $uri $uri/ /index.html;
    index index.html;
  }
}