#cloud-config
ssh_pwauth: no
users:
  - name: "${USERNAME}"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - "${SSH_KEY}"

package_update: true
packages:
  - docker.io
  - docker-compose-v2

runcmd:
  - [ usermod, -aG, docker, "${USERNAME}" ]