all:
  hosts:
    kittygram:
      ansible_host: "{{ target_ip }}"
      ansible_user: "{{ target_user }}"
      ansible_become: yes
      ansible_python_interpreter: /opt/venv/bin/python
      app_dir: "/home/{{ ansible_user }}/kittygram"
